//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.ProdutoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PRODUTO", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class PRODUTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVC.ProdutoServiceReference.CLIENTE CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisponivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVC.ProdutoServiceReference.CLIENTE CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Disponivel {
            get {
                return this.DisponivelField;
            }
            set {
                if ((this.DisponivelField.Equals(value) != true)) {
                    this.DisponivelField = value;
                    this.RaisePropertyChanged("Disponivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdutoId {
            get {
                return this.ProdutoIdField;
            }
            set {
                if ((this.ProdutoIdField.Equals(value) != true)) {
                    this.ProdutoIdField = value;
                    this.RaisePropertyChanged("ProdutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLIENTE", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class CLIENTE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ATIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVC.ProdutoServiceReference.PRODUTO[] PRODUTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobrenomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ATIVO {
            get {
                return this.ATIVOField;
            }
            set {
                if ((this.ATIVOField.Equals(value) != true)) {
                    this.ATIVOField = value;
                    this.RaisePropertyChanged("ATIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVC.ProdutoServiceReference.PRODUTO[] PRODUTO {
            get {
                return this.PRODUTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUTOField, value) != true)) {
                    this.PRODUTOField = value;
                    this.RaisePropertyChanged("PRODUTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sobrenome {
            get {
                return this.SobrenomeField;
            }
            set {
                if ((object.ReferenceEquals(this.SobrenomeField, value) != true)) {
                    this.SobrenomeField = value;
                    this.RaisePropertyChanged("Sobrenome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProdutoServiceReference.IProdutoService")]
    public interface IProdutoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAll", ReplyAction="http://tempuri.org/IProdutoService/FindAllResponse")]
        MVC.ProdutoServiceReference.PRODUTO[] FindAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAll", ReplyAction="http://tempuri.org/IProdutoService/FindAllResponse")]
        System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO[]> FindAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Find", ReplyAction="http://tempuri.org/IProdutoService/FindResponse")]
        MVC.ProdutoServiceReference.PRODUTO Find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Find", ReplyAction="http://tempuri.org/IProdutoService/FindResponse")]
        System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO> FindAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/New", ReplyAction="http://tempuri.org/IProdutoService/NewResponse")]
        MVC.ProdutoServiceReference.PRODUTO New(MVC.ProdutoServiceReference.PRODUTO produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/New", ReplyAction="http://tempuri.org/IProdutoService/NewResponse")]
        System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO> NewAsync(MVC.ProdutoServiceReference.PRODUTO produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Update", ReplyAction="http://tempuri.org/IProdutoService/UpdateResponse")]
        MVC.ProdutoServiceReference.PRODUTO Update(MVC.ProdutoServiceReference.PRODUTO produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Update", ReplyAction="http://tempuri.org/IProdutoService/UpdateResponse")]
        System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO> UpdateAsync(MVC.ProdutoServiceReference.PRODUTO produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/DeleteId", ReplyAction="http://tempuri.org/IProdutoService/DeleteIdResponse")]
        MVC.ProdutoServiceReference.PRODUTO DeleteId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/DeleteId", ReplyAction="http://tempuri.org/IProdutoService/DeleteIdResponse")]
        System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO> DeleteIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Delete", ReplyAction="http://tempuri.org/IProdutoService/DeleteResponse")]
        MVC.ProdutoServiceReference.PRODUTO Delete(MVC.ProdutoServiceReference.PRODUTO produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Delete", ReplyAction="http://tempuri.org/IProdutoService/DeleteResponse")]
        System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO> DeleteAsync(MVC.ProdutoServiceReference.PRODUTO produto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutoServiceChannel : MVC.ProdutoServiceReference.IProdutoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoServiceClient : System.ServiceModel.ClientBase<MVC.ProdutoServiceReference.IProdutoService>, MVC.ProdutoServiceReference.IProdutoService {
        
        public ProdutoServiceClient() {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC.ProdutoServiceReference.PRODUTO[] FindAll() {
            return base.Channel.FindAll();
        }
        
        public System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO[]> FindAllAsync() {
            return base.Channel.FindAllAsync();
        }
        
        public MVC.ProdutoServiceReference.PRODUTO Find(int id) {
            return base.Channel.Find(id);
        }
        
        public System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO> FindAsync(int id) {
            return base.Channel.FindAsync(id);
        }
        
        public MVC.ProdutoServiceReference.PRODUTO New(MVC.ProdutoServiceReference.PRODUTO produto) {
            return base.Channel.New(produto);
        }
        
        public System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO> NewAsync(MVC.ProdutoServiceReference.PRODUTO produto) {
            return base.Channel.NewAsync(produto);
        }
        
        public MVC.ProdutoServiceReference.PRODUTO Update(MVC.ProdutoServiceReference.PRODUTO produto) {
            return base.Channel.Update(produto);
        }
        
        public System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO> UpdateAsync(MVC.ProdutoServiceReference.PRODUTO produto) {
            return base.Channel.UpdateAsync(produto);
        }
        
        public MVC.ProdutoServiceReference.PRODUTO DeleteId(int id) {
            return base.Channel.DeleteId(id);
        }
        
        public System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO> DeleteIdAsync(int id) {
            return base.Channel.DeleteIdAsync(id);
        }
        
        public MVC.ProdutoServiceReference.PRODUTO Delete(MVC.ProdutoServiceReference.PRODUTO produto) {
            return base.Channel.Delete(produto);
        }
        
        public System.Threading.Tasks.Task<MVC.ProdutoServiceReference.PRODUTO> DeleteAsync(MVC.ProdutoServiceReference.PRODUTO produto) {
            return base.Channel.DeleteAsync(produto);
        }
    }
}
